version: 2.1

cache_key: &cache_key node-library-20201223-{{ checksum "yarn.lock" }}

jobs:
  lint-build-test:
    docker:
      - image: cimg/node:lts
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn cache
          keys:
            - *cache_key
      - run:
          name: Install dependencies
          command: .circleci/yarn_frozen_lockfile.sh
      - save_cache:
          name: Save yarn cache
          key: *cache_key
          paths:
            - node_modules/
      - run:
          name: lint
          command: yarn lint
      - run:
          name: build packages
          command: yarn build
      - run:
          name: run tests
          command: yarn test:ci

workflows:
  build-test:
    jobs:
      - lint-build-test
