version: 2

aliases:
  - &restore_cache
    name: Restore yarn cache
    keys:
      - node-library-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/repo

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Make scripts executable
          command: chmod -R +x .circleci/
      - run:
          name: Install dependencies
          command: .circleci/yarn_frozen_lockfile.sh
      - save_cache:
          name: Save yarn cache
          key: node-library-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.cache

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: build
          command: yarn build

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: lint
          command: yarn lint

  check-types:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: check-types
          command: yarn check-types

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: test
          command: yarn test

workflows:
  version: 2
  build-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - check-types:
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
            - build
            - check-types
            - lint
