version: 2.1

executors:
  docker:
    docker:
      - image: cimg/node:lts

aliases:
  - &restore_cache
    name: Restore yarn cache
    keys:
      - node-library-20200807-{{ checksum "yarn.lock" }}

jobs:
  install:
    executor: docker
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Install dependencies
          command: .circleci/yarn_frozen_lockfile.sh
      - save_cache:
          name: Save yarn cache
          key: node-library-20200807-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  build:
    executor: docker
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: build
          command: yarn build

  lint:
    executor: docker
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: lint
          command: yarn lint

  test:
    executor: docker
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: test
          command: yarn test:ci

workflows:
  build-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
